<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup><ItemGroup><ProjectReference Include="../GpSelect.Domain/GpSelect.Domain.csproj"/><ProjectReference Include="../GpSelect.Application/GpSelect.Application.csproj"/><PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.20"/><PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.20" PrivateAssets="all"/><PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.8"/><PackageReference Include="SixLabors.ImageSharp" Version="3.1.11"/><PackageReference Include="AWSSDK.S3" Version="3.7.309.1"/><PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.1"/></ItemGroup></Project>

