using GpSelect.Domain; using Microsoft.EntityFrameworkCore; using Microsoft.Extensions.Configuration; using Amazon.S3; using Amazon.S3.Model; using Microsoft.Extensions.DependencyInjection;
namespace GpSelect.Infrastructure;
public sealed class GpSelectDbContext(DbContextOptions<GpSelectDbContext> options):DbContext(options){ public DbSet<VehicleUnit> Vehicles=>Set<VehicleUnit>(); public DbSet<VehicleImage> Images=>Set<VehicleImage>(); public DbSet<ImageProcessingJob> ImageJobs=>Set<ImageProcessingJob>(); public DbSet<IdempotencyRecord> IdempotencyRecords=>Set<IdempotencyRecord>(); public DbSet<Enquiry> Enquiries=>Set<Enquiry>(); protected override void OnModelCreating(ModelBuilder b){ b.Entity<Enquiry>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.Intent).HasConversion<string>().HasMaxLength(20);e.Property(x=>x.NotificationStatus).HasConversion<string>().HasMaxLength(20);e.Property(x=>x.Name).HasMaxLength(Enquiry.NameMax);e.Property(x=>x.Email).HasMaxLength(Enquiry.EmailMax);e.Property(x=>x.Phone).HasMaxLength(Enquiry.PhoneMax);e.Property(x=>x.Vehicle).HasMaxLength(Enquiry.VehicleMax);e.Property(x=>x.Message).HasMaxLength(Enquiry.MessageMax);e.HasIndex(x=>x.CreatedAt);e.HasIndex(x=>new{x.NotificationStatus,x.NotificationNextAttemptAt});}); b.Entity<VehicleUnit>().HasKey(x=>x.Id); b.Entity<VehicleUnit>().HasIndex(x=>x.PublicSlug).IsUnique(); b.Entity<VehicleUnit>().Property(x=>x.PriceEur).HasPrecision(18,2); b.Entity<VehicleUnit>().Property(x=>x.PurchaseCostEur).HasPrecision(18,2); b.Entity<VehicleUnit>().Property(x=>x.Status).HasConversion<string>(); b.Entity<VehicleImage>().HasKey(x=>x.Id); b.Entity<VehicleImage>().Property(x=>x.State).HasConversion<string>(); b.Entity<VehicleImage>().HasIndex(x=>x.VehicleUnitId).HasFilter("\"IsCover\" = TRUE AND \"State\" <> 'Deleted'").IsUnique(); b.Entity<VehicleUnit>().HasMany<VehicleImage>().WithOne().HasForeignKey(x=>x.VehicleUnitId); b.Entity<ImageProcessingJob>().HasKey(x=>x.Id); b.Entity<ImageProcessingJob>().HasOne<VehicleImage>().WithMany().HasForeignKey(x=>x.ImageId).OnDelete(DeleteBehavior.Cascade); b.Entity<ImageProcessingJob>().Property(x=>x.State).HasConversion<string>(); b.Entity<ImageProcessingJob>().HasIndex(x=>new{x.State,x.NextAttemptAt}); b.Entity<IdempotencyRecord>().HasKey(x=>x.Id); b.Entity<IdempotencyRecord>().HasIndex(x=>new{x.Operation,x.Key}).IsUnique(); b.Entity<IdempotencyRecord>().Property(x=>x.ResponseJson).HasColumnType("jsonb"); } }
public sealed class IdempotencyRecord { public Guid Id {get;set;}=Guid.NewGuid(); public string Operation {get;set;}=""; public string Key {get;set;}=""; public string RequestHash {get;set;}=""; public int StatusCode {get;set;} public string ResponseJson {get;set;}=""; public DateTimeOffset CreatedAt {get;set;}=DateTimeOffset.UtcNow; }
public sealed record ObjectMetadata(long SizeBytes,string ContentType);
public interface IObjectStorage { Task<string> CreateUploadUrlAsync(string key,string mime,CancellationToken ct); Task<ObjectMetadata?> HeadAsync(string key,CancellationToken ct); Task<Stream> OpenReadAsync(string key,CancellationToken ct); Task PutAsync(string key,Stream content,string mime,CancellationToken ct); Task DeleteAsync(string key,CancellationToken ct); }
public sealed class FileObjectStorage(IConfiguration config):IObjectStorage { private string Root=>config["Storage:Root"]??Path.Combine(AppContext.BaseDirectory,"uploads"); private string PathFor(string key){if(string.IsNullOrWhiteSpace(key)||key.Contains("..",StringComparison.Ordinal)||Path.IsPathRooted(key)||key.Contains('\\')||!(key.StartsWith("quarantine/",StringComparison.Ordinal)||key.StartsWith("vehicles/",StringComparison.Ordinal)))throw new InvalidOperationException("Invalid object key");return Path.Combine(Root,key.Replace('/',Path.DirectorySeparatorChar));} public Task<string>CreateUploadUrlAsync(string key,string mime,CancellationToken ct)=>Task.FromResult($"/api/admin/uploads/{key}"); public Task<ObjectMetadata?> HeadAsync(string key,CancellationToken ct){var p=PathFor(key);return Task.FromResult<ObjectMetadata?>(File.Exists(p)?new ObjectMetadata(new FileInfo(p).Length,DetectMime(p)):null);} private static string DetectMime(string p)=>Path.GetExtension(p).ToLowerInvariant() switch {".jpg" or ".jpeg"=>"image/jpeg",".png"=>"image/png",".webp"=>"image/webp",_=>"application/octet-stream"}; public Task<Stream>OpenReadAsync(string key,CancellationToken ct)=>Task.FromResult<Stream>(new FileStream(PathFor(key),FileMode.Open,FileAccess.Read,FileShare.Read,65536,true)); public async Task PutAsync(string key,Stream content,string mime,CancellationToken ct){var p=PathFor(key);Directory.CreateDirectory(Path.GetDirectoryName(p)!);await using var f=new FileStream(p,FileMode.Create,FileAccess.Write,FileShare.None,65536,true);await content.CopyToAsync(f,ct);} public Task DeleteAsync(string key,CancellationToken ct){var p=PathFor(key);if(File.Exists(p))File.Delete(p);return Task.CompletedTask;} }
public sealed class S3ObjectStorage(IConfiguration c):IObjectStorage { readonly IAmazonS3 s3=new AmazonS3Client(c["Storage:AccessKey"],c["Storage:SecretKey"],new AmazonS3Config{ServiceURL=c["Storage:Endpoint"],ForcePathStyle=true}); string Bucket=>c["Storage:Bucket"]??throw new InvalidOperationException("Storage:Bucket is required"); public Task<string>CreateUploadUrlAsync(string key,string mime,CancellationToken ct)=>Task.FromResult(s3.GetPreSignedURL(new GetPreSignedUrlRequest{BucketName=Bucket,Key=key,Verb=HttpVerb.PUT,ContentType=mime,Expires=DateTime.UtcNow.AddMinutes(15)})); public async Task<ObjectMetadata?> HeadAsync(string key,CancellationToken ct){try{var x=await s3.GetObjectMetadataAsync(Bucket,key,ct);return new(x.ContentLength,x.Headers.ContentType);}catch(Amazon.S3.AmazonS3Exception e) when(e.StatusCode==System.Net.HttpStatusCode.NotFound){return null;}} public async Task<Stream>OpenReadAsync(string key,CancellationToken ct)=>(await s3.GetObjectAsync(Bucket,key,ct)).ResponseStream; public Task PutAsync(string key,Stream content,string mime,CancellationToken ct)=>s3.PutObjectAsync(new PutObjectRequest{BucketName=Bucket,Key=key,InputStream=content,ContentType=mime,AutoCloseStream=false},ct); public Task DeleteAsync(string key,CancellationToken ct)=>s3.DeleteObjectAsync(Bucket,key,ct); }




