using GpSelect.Domain; using Xunit;
namespace GpSelect.Tests;
public class VehicleTests {
 [Fact] public void Draft_can_be_incomplete(){var v=VehicleUnit.Create("Porsche","911",2020,null,"porsche-911-x");Assert.Equal(VehicleStatus.Draft,v.Status);}
 [Fact] public void Registration_month_is_optional(){var v=VehicleUnit.Create("A","B",2020,null,"a-b-x");Assert.Null(v.FirstRegistrationMonth);}
 [Fact] public void Archived_needs_restoring_before_publishing(){var v=VehicleUnit.Create("A","B",2020,null,"a-b-x");v.Archive();Assert.Throws<DomainException>(()=>v.ChangeStatus(VehicleStatus.Available,[]));}
 [Fact] public void Publish_requires_ready_cover(){var v=VehicleUnit.Create("A","B",2020,null,"a-b-x");Assert.Throws<DomainException>(()=>v.Publish([]));}
 [Fact] public void Money_is_decimal(){var propertyType=typeof(VehicleUnit).GetProperty("PriceEur")!.PropertyType;Assert.Equal(typeof(decimal),Nullable.GetUnderlyingType(propertyType)??propertyType);}
 [Fact] public void Deleted_image_cannot_be_revived_by_worker(){var image=VehicleImage.Create(Guid.NewGuid(),"quarantine/x.jpg","image/jpeg",10);image.Delete();image.Ready("vehicles/x/card.jpg","vehicles/x/detail.jpg");image.Fail("late worker");Assert.Equal(ImageState.Deleted,image.State);}
 [Fact] public void Public_card_prefers_ready_cover_then_sorts_ready_card_images(){var v=VehicleUnit.Create("Porsche","911",2020,null,"porsche-911-x");var cover=VehicleImage.Create(v.Id,"cover.jpg","image/jpeg",10);cover.Ready("cover-card.jpg","cover-detail.jpg");cover.SetCover(true);cover.Order(99);var early=VehicleImage.Create(v.Id,"early.jpg","image/jpeg",10);early.Ready("early-card.jpg","early-detail.jpg");early.Order(1);var late=VehicleImage.Create(v.Id,"late.jpg","image/jpeg",10);late.Ready("late-card.jpg","late-detail.jpg");late.Order(5);var result=GpSelect.Application.PublicMapping.MapCard(v,new[]{late,cover,early});Assert.Equal(new[]{"/api/public/vehicles/porsche-911-x/images/"+cover.Id+"/card","/api/public/vehicles/porsche-911-x/images/"+early.Id+"/card","/api/public/vehicles/porsche-911-x/images/"+late.Id+"/card"},result.Images);}
 [Fact] public void Public_card_excludes_non_ready_and_missing_card_images(){var v=VehicleUnit.Create("Porsche","911",2020,null,"porsche-911-x");var ready=VehicleImage.Create(v.Id,"ready.jpg","image/jpeg",10);ready.Ready("ready-card.jpg","ready-detail.jpg");var failed=VehicleImage.Create(v.Id,"failed.jpg","image/jpeg",10);failed.Ready("failed-card.jpg","failed-detail.jpg");failed.Fail("processing failed");var missingCard=VehicleImage.Create(v.Id,"missing.jpg","image/jpeg",10);missingCard.Ready(null!,"missing-detail.jpg");var result=GpSelect.Application.PublicMapping.MapCard(v,new[]{failed,missingCard,ready});Assert.Single(result.Images);Assert.Contains(ready.Id.ToString(),result.Images[0]);}
 [Fact] public void Admin_detail_contract_contains_all_editable_fields(){var editable=new[]{"Description","MileageKm","Variant","FuelType","Transmission","BodyType","ExteriorColour","Interior","History","Provenance","Equipment","CustomSpecifications","PowerHp","Drivetrain"};var properties=typeof(GpSelect.Application.VehicleAdminDto).GetProperties().Select(x=>x.Name);Assert.All(editable,field=>Assert.Contains(field,properties));}
}
